---
title: "abcd pub smri - post analysis"
author: "cfm"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
---

### setting up markdown {.tabset}

```{r setup, include=FALSE}

knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)

options(scipen=999)
```

### loading required packages

```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}

library(pacman)

pacman::p_load(dplyr, ggplot2, tidyr, lubridate, data.table, ggseg, ggseg3d, htmlwidgets, ggpattern, install = TRUE)


library("ggseg")

coronal <- "coronal"

```

# setting up

```{r root path}

proj_root = ".../projects/abcd-projs/smri-pub-abcd/"
data_root = ".../projects/abcd-projs/smri-pub-abcd/results/"

```


```{r data}

timing <- read.csv(paste0(proj_root, "results/cleaned/combat_timing_pvals.csv")) 
tempo <- read.csv(paste0(proj_root, "results/cleaned/combat_tempo_pvals.csv")) 
```

```{r best-fitting model}


metrics <- c("thick", "area", "vol")
pubs <- c("timing", "tempo")

for (pub in pubs) {
  for (metric_value in metrics) {
    
      if (pub == "timing") {
          colors <- c("#40c9ff", "#fc9305", "#f20094")
          plot_data <- timing %>% 
            filter(metric == !!metric_value) %>% 
            #filter(sig == 1) %>%  
            filter(
              (model == "age_model" &
               rowname == "s(age_scaled)" &
               !!sym(paste0("overall_best_", pub, "_model")) == "age_model") |
                
              (model == "age_timing_main_model" &
               rowname == "timing_scaled" &
               !!sym(paste0("overall_best_", pub, "_model")) == "age_timing_main_model") |
              
              (model == "age_timing_int_model" &
               rowname == "s(age_scaled):timing_scaled" &
               !!sym(paste0("overall_best_", pub, "_model")) == "age_timing_int_model")
            ) %>%
            mutate(model = case_when(
              model == "age_model" ~ "model 1 (age only)",
              model == "age_timing_main_model" ~ "model 2 (timing main effect)",
              model == "age_timing_int_model" ~ "model 3 (interaction effect)",
              TRUE ~ model
            )) %>%
          filter(!is.na(sex)) %>%
          select(-region) %>%
          rename("region" = "region.name") %>% 
          mutate(sig = as.logical(sig),
                 significance_pattern = if_else(sig, "solid", "lines")
)
      } else if (pub == "tempo") {
          colors <- c("#40c9ff", "#e81cff","#a9ff68")
          plot_data <- tempo %>% 
            filter(metric == !!metric_value) %>% 
            #filter(sig == 1) %>%  
            filter(
              (model == "age_model" &
               rowname == "s(age_scaled)" &
               !!sym(paste0("overall_best_", pub, "_model")) == "age_model") |
                
              (model == "age_tempo_main_model" &
               rowname == "tempo_scaled" &
               !!sym(paste0("overall_best_", pub, "_model")) == "age_tempo_main_model") |
              
              (model == "age_tempo_int_model" &
               rowname == "s(age_scaled):tempo_scaled" &
               !!sym(paste0("overall_best_", pub, "_model")) == "age_tempo_int_model")
            ) %>%
            mutate(model = case_when(
              model == "age_model" ~ "model 1 (age only)",
              model == "age_tempo_main_model" ~ "model 2 (tempo main effect)",
              model == "age_tempo_int_model" ~ "model 3 (interaction effect)",
              TRUE ~ model
            )) %>%
          filter(!is.na(sex)) %>%
          select(-region) %>%
          rename("region" = "region.name") %>% 
          mutate(sig = as.logical(sig),
                 significance_pattern = if_else(sig, "solid", "lines")
)

      }
      
      if (metric_value == "thick" || metric_value == "area") {
        atlas_choice <- dk
      } else if (metric_value == "vol") {
        atlas_choice <- aseg
      }


      if (metric_value %in% c("thick", "area")) {
        
        atlas_sf <- dk$data
        
        plot_data_sf <- atlas_sf %>%
          left_join(plot_data, by = c("region", "hemi"))
        
        pub_plot <- plot_data %>%
          group_by(sex) %>% 
          ggplot() +
          geom_brain(atlas = atlas_choice, 
                     aes(fill = model, alpha = sig),
                     position = position_brain(hemi ~ side)) + 
          scale_fill_manual(values = colors) +
          scale_alpha_manual(
                     values = c(`TRUE` = 1, `FALSE` = 0.5)
                   ) +
          theme_minimal() +
          facet_wrap(~ as.factor(sex)) +
          theme(axis.text.x = element_blank(), 
                axis.text.y = element_blank(), 
                axis.ticks = element_blank(), 
                panel.background = element_rect(fill = "transparent", color = NA),
                plot.background = element_rect(fill = "transparent", color = NA),
                legend.background = element_blank(),
                legend.key = element_blank(), 
                legend.key.size = unit(1.2, "lines"),
                text = element_text(family = "Times", color = "black", size = 22),
                plot.title = element_text(family = "Times", size = 22),
                legend.position = "none")
        
      print(pub_plot)

      ggsave(pub_plot,
             filename = paste0(data_root, "plots/ggseg/best_fit_", pub, "_", metric_value, "_brain_plot.svg"),
             width = 8,
             height = 8,
             units = 'in',
             dpi = 300)
        
      } else {  # volume
        
        pub_plot <- plot_data %>%
          group_by(sex) %>% 
          ggplot() +
          geom_brain(atlas = atlas_choice, 
                     aes(fill = model, alpha = sig)) + 
          scale_fill_manual(values = colors) + 
          scale_alpha_manual(
                     values = c(`TRUE` = 1, `FALSE` = 0.5)
                   ) +
          theme_minimal() +
          facet_wrap(~ as.factor(sex)) +
          theme(axis.text.x = element_blank(), 
                axis.text.y = element_blank(), 
                axis.ticks = element_blank(), 
                panel.background = element_rect(fill = "transparent", color = NA),
                plot.background = element_rect(fill = "transparent", color = NA),
                legend.background = element_blank(),
                legend.key = element_blank(), 
                legend.key.size = unit(1.2, "lines"),
                text = element_text(family = "Times", color = "black", size = 22),
                plot.title = element_text(family = "Times", size = 22),
                legend.position = "none")
        
      print(pub_plot)

      ggsave(pub_plot,
             filename = paste0(data_root, "plots/ggseg/best_fit_", pub, "_", metric_value, "_brain_plot.svg"),
             width = 8,
             height = 8,
             units = 'in',
             dpi = 300)

      
      
      }

    }
  }



```